# Generated by Django 3.2 on 2021-04-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210418_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaside',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
